$(document).ready(function(){
  $('#b1').click(function(){
    $('.header').slideUp(1000);
  });
    $('#b1').click(function(){
      $('.message').show(1000);
    });
    $('#b2').click(function(){
      $('.message2').show(1000);
    });
    $('#b2').click(function(){
      $('.header').hide();
    });
    $('#b1').click(function(){
      $('.message2').hide();
    });
    $('#b2').click(function(){
      $('.message').hide();
    });
    $('#b1').click(function(){
      $('.home').show();
    });
    $('#b2').click(function(){
      $('.home').show();
    });
    $('.home').click(function(){
      $('.header').show();
    });
    $('.home').click(function(){
      $('.message').hide();
    });
    $('.home').click(function(){
      $('.message2').hide();
    });
    $('.home').click(function(){
      $('.home').hide();
    });
});
